name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update system
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
      - name: Setup ssh client
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no "kraftwerk28@kraftwerk28.pp.ua" "ls"
      - name: Build image
        run: |
          docker login -u "kraftwerk28" -p "${{ secrets.DOCKER_PASS }}"
          PORT=1495 docker-compose build
          docker-compose push
      - name: Deploy on server
        run: |
          docker-compose --version
          export DOCKER_HOST="ssh://kraftwerk28@kraftwerk28.pp.ua"
          docker-compose pull
          PORT=1495 docker-compose up -d
