name: CI

on: [push]

env:
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}
  SSHURL: "ssh://$USER@$HOST"
  SSH_PK: ${{ secrets.SSH_PRIV_KEY }}
  DOCKER_USER: ${{ secrets.USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: |
          sudo mkdir -p "/usr/local/bin/docker"
          sudo curl \
            -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Setup ssh client
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PK" >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no "$USER@$HOST" "pwd"
      - name: Build image
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          docker-compose build
          docker-compose push
      - name: Deploy on server
        run: |
          docker-compose -H $SSHURL pull
          PORT=1495 docker-compose -H $SSHURL up -d
