name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup ssh client
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIV_KEY }}" >> ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh "kraftwerk28@kraftwerk28.pp.ua" "ls"
        ssh "kraftwerk28@kraftwerk28.pp.ua" "ls -lhs"
#     - name: Build image
#       run: |
#         docker-compose build
#         docker-compose push
#     - name: Deploy on server
#       run: |
#         docker-compose -H "ssh://kraftwerk28.pp.ua" pull
#         docker-compose -H "ssh://kraftwerk28.pp.ua" up -d
