name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#     - uses: webfactory/ssh-agent@v0.1.1
#       with:
#         ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
    - name: Setup ssh client
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIV_KEY }}" >> ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa "kraftwerk28@kraftwerk28.pp.ua" "ls"
